sonar.projectKey=fuchi-no-dokuneko_fuchi-no-dokuneko.github.io
sonar.projectName=fuchi-no-dokuneko.github.io
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=tests
sonar.exclusions=.git/**,.github/**,build/**,tests/**,vendor/**
sonar.test.inclusions=tests/**
sonar.coverage.exclusions=scripts/**,tests/**,vendor/**
sonar.javascript.lcov.reportPaths=build/reports/browser-uat/lcov.info
sonar.testExecutionReportPaths=build/reports/browser-uat/sonar-test-execution.xml
